---
name: 🪄 Autofix
"on":
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  autofix:
    uses: kdeldycke/repomatic/.github/workflows/autofix.yaml@ac35a90ce5322a4e4593ae0db7cf348cec80952f # v6.10.0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
