---
name: ✂️ Cancel runs
"on":
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:

  cancel-runs:
    uses: kdeldycke/repomatic/.github/workflows/cancel-runs.yaml@0a4d6470fbbb69496f742e7fe14a706b3ebc2060 # v6.11.0
