---
name: 🆙 Changelog & versions
"on":
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - "Build & release"
    types:
      - completed
    branches:
      - main

jobs:

  changelog:
    uses: kdeldycke/repomatic/.github/workflows/changelog.yaml@v6.7.0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
      WORKFLOW_UPDATE_GITHUB_PAT: ${{ secrets.WORKFLOW_UPDATE_GITHUB_PAT }}
