---
name: 📚 Docs
"on":
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  docs:
    uses: kdeldycke/repomatic/.github/workflows/docs.yaml@ac35a90ce5322a4e4593ae0db7cf348cec80952f # v6.10.0
