---
name: 📚 Docs
"on":
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  docs:
    uses: kdeldycke/repomatic/.github/workflows/docs.yaml@204a868c5345477f62a29715d2838ac1c6daa3ee # v6.9.0
